// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: server.proto

package service

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetData_GetData_FullMethodName = "/GetData/GetData"
)

// GetDataClient is the client API for GetData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
// 定义了一个 SayHello 服务
type GetDataClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
}

type getDataClient struct {
	cc grpc.ClientConnInterface
}

func NewGetDataClient(cc grpc.ClientConnInterface) GetDataClient {
	return &getDataClient{cc}
}

func (c *getDataClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, GetData_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetDataServer is the server API for GetData service.
// All implementations must embed UnimplementedGetDataServer
// for forward compatibility.
//
// 定义服务
// 定义了一个 SayHello 服务
type GetDataServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	mustEmbedUnimplementedGetDataServer()
}

// UnimplementedGetDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetDataServer struct{}

func (UnimplementedGetDataServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedGetDataServer) mustEmbedUnimplementedGetDataServer() {}
func (UnimplementedGetDataServer) testEmbeddedByValue()                 {}

// UnsafeGetDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetDataServer will
// result in compilation errors.
type UnsafeGetDataServer interface {
	mustEmbedUnimplementedGetDataServer()
}

func RegisterGetDataServer(s grpc.ServiceRegistrar, srv GetDataServer) {
	// If the following call panics, it indicates UnimplementedGetDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetData_ServiceDesc, srv)
}

func _GetData_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetDataServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetData_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetDataServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetData_ServiceDesc is the grpc.ServiceDesc for GetData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetData",
	HandlerType: (*GetDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _GetData_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
